name: CI

on:
  workflow_dispatch:
    types: ManualUpdate
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Linux Executable
      run: |
        pip3 install PyInstaller
        cd ${GITHUB_WORKSPACE} && python3 -m PyInstaller --onefile -w src/tcg-to-deckbox.py --add-data "src/replacements.config:.""

  release-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Windows Executable
      run: |
        pip3 install PyInstaller
        cd ${GITHUB_WORKSPACE} && python3 -m PyInstaller --onefile -w src/tcg-to-deckbox.py --add-data"src/replacements.config;.""